name: "Bump new version"
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.bump_type }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Bumping version to: $VERSION"

      - name: Create and push release branch
        run: |
          git checkout -b release
          git add package.json
          git commit -m "Bump version to ${{ env.VERSION }}"
          git push origin release --force
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build changelog
        id: github_release_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/changelog-configuration.json"
          toTag: "refs/heads/main"
          failOnError: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release draft
        id: create-release
        uses: actions/github-script@v7
        env:
          changelog: ${{ steps.github_release_changelog.outputs.changelog }}
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.VERSION}`,
              name: `v${process.env.VERSION}`,
              body: process.env.changelog,
              draft: true,
              prerelease: process.env.VERSION.indexOf('alpha') >= 0,
            })
            return data.id

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [create-release-branch]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: npm install

      - name: Install tsc-alias
        run: npm i -g tsc-alias

      - name: Build
        run: npm run build

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish release
        id: publish-release
        uses: actions/github-script@v7
        env:
          release_id: ${{ needs.create-release-branch.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
            })

  update-main-branch-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [publish]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push version update to main
        run: |
          git checkout main
          git merge release --ff-only  # 或者使用 cherry-pick 获取版本更新的 commit
          git push origin main

  cleanup-release-branch:
    needs: [publish]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: success()
    steps:
      - name: Delete release branch
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/release'
            })
